name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        server-id: central
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        
    - name: Update version in pom.xml
      run: |
        RELEASE_VERSION=$(echo ${{ github.event.release.tag_name }} | sed 's/^v//')
        mvn versions:set -DnewVersion=${RELEASE_VERSION} -DgenerateBackupPoms=false

    - name: Build and publish to Maven Central
      run: mvn clean deploy -P release -Dquarkus.profile=chappie -DskipTests
      env:
        MAVEN_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
